### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by jpcaveiro** [djangocon/2024.djangocon.eu#19]
Instead of redirecting to

- https://2024.djangocon.eu/talks/schedule/djangoconeurope.slack.com
 
it should redirect to

- https://djangoconeurope.slack.com

in here

https://github.com/djangocon/2024.djangocon.eu/blob/f2b2a9cde27b590b36aa5a44fa0d4aab1ada3619/djangocon_2024/content/talks/cfp/1schedule.md?plain=1#L8

**Comment by Darkbeast-glitch** [comment]
Seen sir, will fix it right away

**Comment by Darkbeast-glitch** [comment]
Hey @jpcaveiro  i think we are already redirecting you to the right Slack channel.
kindly check as  I don't see any changes to be made. Thank you

**Comment by jpcaveiro** [comment]
There are two "Slack" words with links  in the page https://2024.djangocon.eu/talks/cfp/. 

The first "Slack" link works well.

<img width="403" alt="image" src="https://github.com/djangocon/2024.djangocon.eu/assets/11158247/66b5c99f-6b45-4a48-b335-87b0426bf4fe">

The second "Slack" word in here:

<img width="737" alt="image" src="https://github.com/djangocon/2024.djangocon.eu/assets/11158247/3db96e4d-e927-4ada-8da1-96bd00b6d68d">

produce this URL (seen at bottom of the browser): 

<img width="285" alt="image" src="https://github.com/djangocon/2024.djangocon.eu/assets/11158247/3b10a62c-77ed-42c6-a678-311d461f0715">

Notes:

* I've pressed the "refresh" browser button a couple of times before testing.
* Where is the most appropriate "forum" for django community questions? (I'm starting.)

**Comment by Darkbeast-glitch** [comment]
Seen, will work on that, thanks

**Comment by jpcaveiro** [comment]
It works. Thank you for your time.

**Comment by Darkbeast-glitch** [comment]
You are welcome sir , we can close this issue now,
