### ISSUE TITLE
Set `DEBUG = False`

### ISSUE THREAD

**Issue by tobiasmcnulty** [djangocon/2024.djangocon.eu#41]
Hello! I noticed DEBUG is enabled, and there is also a 404 from the https://2024.djangocon.eu/tickets/ page (not sure how I got to that, it might have been a direct Google result as I don't see it linked in the header currently).

<img width="916" alt="Screenshot 2024-04-01 at 12 22 29 PM" src="https://github.com/djangocon/2024.djangocon.eu/assets/160132/ef5b72c4-f62c-461b-a8a3-0b50d5c10775">

Thanks, and I look forward to the conference!

**Comment by Darkbeast-glitch** [comment]
Thank you sir,
