### ISSUE TITLE
Clarify how to gain access to Slack

### ISSUE THREAD

**Issue by tobiasmcnulty** [djangocon/2024.djangocon.eu#42]
Hello again! I see a few links to https://djangoconeurope.slack.com/ on the site, but when I navigate there and attempt to sign up I am told I need a specific email domain to access the instance.

How does one go about requesting an invite, and could this be published somewhere on the site (if it's not intentionally being kept private, at least)?

<img width="726" alt="Screenshot 2024-04-01 at 12 23 32 PM" src="https://github.com/djangocon/2024.djangocon.eu/assets/160132/be9f2671-6c75-4061-9907-dafb59b48275">

**Comment by Darkbeast-glitch** [comment]
Hello @tobiasmcnulty , please I understand the error and sorry for that.
I will return with a solution , you probably need an invite from someone already in the channel

**Comment by Darkbeast-glitch** [comment]
Hello @tobiasmcnulty , so about your issue on joining the slack, we seems to have some limitation on our workspace, which is preventing us to invite more people , kindly hold on as we get it fixed or find our way around this.
Thank you very much for understanding .

I will close the issue now please

**Comment by tobiasmcnulty** [comment]
@Darkbeast-glitch Thanks for the response! I just tried to sign up again, but I'm still getting the same error. Is there a way to request an invitation in the meantime?
