### ISSUE TITLE
[BUG] The charts in the 'Schedule' page should span the whole row

### ISSUE THREAD

**Issue by sakhawy** [djangocon/2024.djangocon.eu#44]
This is how it currently looks.
![image](https://github.com/djangocon/2024.djangocon.eu/assets/50373064/d979539d-01b5-4daa-8549-bd7dde4efb22)

I inspected the elements and changed the outer div from `col-md-4` to `col-md-12` and it made more sense:
![image](https://github.com/djangocon/2024.djangocon.eu/assets/50373064/a0fa851c-45e3-49a9-bb4c-531dc5f101c3)

**Comment by Darkbeast-glitch** [comment]
Excellent, Thank you,  this is how it was showing on my development and even in production ,I am just expecting and am sure someone tempered with the code, I am still investing and i will revert


![image](https://github.com/djangocon/2024.djangocon.eu/assets/66005635/5c08bb13-1973-4418-a425-df644615e5da)

buh i tested it on all screen before pushing, buh i don't know why it's looking like this

**Comment by Darkbeast-glitch** [comment]
I am sure there is a problem, i will check and revert, @davidmgvaz  can check into it , cause i also just viewed on the website and it doesn't look good buh earlier it was
