### ISSUE TITLE
Django DEBUG mode is still enabled in production environment

### ISSUE THREAD

**Issue by theShinigami** [djangocon/2024.djangocon.eu#51]
It seems **DEBUG** is set to **True**, in production environment.

![image](https://github.com/djangocon/2024.djangocon.eu/assets/56839725/2136bf12-27ec-4c19-9876-2df4704f6313)

**Comment by Darkbeast-glitch** [comment]
Hey @theShinigami  yeah cool thanks for trying your hands on this issue, I will review the solution and fixes in the code you pushed

**Comment by davidmgvaz** [comment]
Just fixed in server side
