### ISSUE TITLE
Home Page Banner/logo section buttons not looking nice

### ISSUE THREAD

**Issue by dostogircse171** [djangocon/2024.djangocon.eu#9]
On the homepage, just below the Djangocon logo there are 2 buttons for now "Submit your CFP📢" and "Buy Tickets🎫".
But these 2 buttons is not same width and the icon need a space in between text. 
This happens the same for mobile when stacked.
 I have attached 2 screenshots below. 

**Desktop:**
<img width="1700" alt="Screenshot 2024-01-08 at 11 50 50 pm" src="https://github.com/djangocon/2024.djangocon.eu/assets/28702192/bf2e73d4-8805-4df7-b60f-1233b9cc4428">
**Mobile:**
<img width="485" alt="Screenshot 2024-01-08 at 11 51 03 pm" src="https://github.com/djangocon/2024.djangocon.eu/assets/28702192/52cb2c4a-bfee-4af8-bfcd-ea586bc62ba4">

**Comment by Darkbeast-glitch** [comment]
Hello sir, I would get that fix real quick
